name: "Build App & Deploy to Github Pages"

on:
  push:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  build_and_deploy:
    name: Build and Deploy
    concurrency:
      group: build-and-deploy
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit -- --run

      - name: Build project
        run: npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
